version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build: ./db
    volumes:
      - db_data:/app
    ports:
      - "6000:6000"

volumes:
  db_data:
